# Generated by Django 5.2.6 on 2025-10-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
